sphuber/aiida-shell

- pyproject.toml
This includes a bugfix that was affecting the pre-commit in CI where `mypy` would fail with the error:
Positional-only parameters are only supported in Python 3.8 and greater
This affected code in `numpy`.
> Dependencies: Update `pre-commit` requirement `mypy==0.981`

- src/aiida_shell/parsers/shell.py
- tests/parsers/test_shell.py
Fixes #8 
Output files are attached using their filename as a link label. However, the validation rules for link labels are a lot more restrictive compared to filenames. The former can only contain alphanumeric characters and non-consecutive underscores.
The `ShellParser` already replaced `.` characters, often found in filenames used for the extension, into underscores, but these are not the only illegal characters for link labels that can occur, such as dashes etc. The parser is updated to replace any invalid character with an underscore where consecutive underscores are merged into one.
> `ShellParser`: Fix output files with non-alphanumeric characters

- src/aiida_shell/calculations/shell.py
- src/aiida_shell/parsers/shell.py
- tests/parsers/test_shell.py
Fixes #14 
Certain shell commands may fail to properly return a non-zero exit code if the command failed. Currently, these shell job's are marked as finished successfully, which can be misleading. Often, the error will be written to stderr which is a marker for the failure.
Here we add the `ERROR_STDERR_NOT_EMPTY` exit code that is returned by the `ShellParser` if the exit status of the command is zero but the stderr is not empty.
> `ShellJob`: Add the `ERROR_STDERR_NOT_EMPTY` exit code

- src/aiida_shell/engine/launchers/shell_job.py
Fixes #9 
The `launch_shell_job` emits a log message on the warning level if no explicit computer is specified and if the `Code` is created automatically. However, given that warnings are always shown with the default logging configuration of AiiDA and that most users will not explicitly specify a code, as that is the whole point of this convenience wrapper, they will get the warning message every time.
Instead, the log message is now emitted on the info level so it won't be shown by default but can be made visible by changing the log level for the AiiDA logger to `INFO`.
> `launch_shell_job`: Change log level from warning to info

- README.md
- src/aiida_shell/engine/launchers/shell_job.py
- tests/calculations/test_shell.py
- tests/conftest.py
- tests/engine/launchers/test_shell_job.py
Fixes #2 
The `submit` argument takes a boolean and when set to `True` the shell job is sent to the daemon instead of run by the current interpreter. If the shell jobs are independent, this allows them to be run in parallel by the daemon workers.
> `launch_shell_job`: Add the `submit` argument to run over the daemon

- src/aiida_shell/calculations/shell.py
- tests/calculations/test_shell.py
- tests/conftest.py
Fixes #7 
This method returns the string that is set as the `process_label` attribute on the nodes representing executions of the process class. By default this is the name of the process class, i.e., `ShellJob` in this case. This is not very informative as all `ShellJob` runs, regardless of the shell command it ran, will get the same label.
Here we override the `_build_process_label` to include the full label of the code, which in turn will include the label (typically the name of the shell command) and the name of the computer on which is was run. An example is `ShellJob<echo@localhost>`.
> `ShellJob`: Customize the `_build_process_label` method

- pyproject.toml
The functionality we were relying on has now been officially released with `aiida-core==2.1` so we can use that as the minimum requirement instead of installing from the repository.
> Dependencies: Update requirement `aiida-core~=2.1`

- README.md
- src/aiida_shell/calculations/shell.py
- tests/calculations/test_shell.py
Fixes #24 
So far the logic for determining the filename used to write the content of the inputs `nodes` in the running directory to, was to first look if an explicit filename was defined in the `filenames` input and otherwise to fallback to the `key` of the node within the `nodes` dictionary.
Here we change the code to use the `filename` of the `SinglefileData` before falling back to the key, if and only if the `filename` of the node is defined and not `SinglefileData.DEFAULT_FILENAME`. This last exception is important because if a `SinglefileData` node is constructed without explicit filename, that value is used, and with this new fule any `SinglefileData` nodes that were created without explicit filename will end up overwriting each other.
> `ShellJob`: Use `SinglefileData.filename` before falling back on key

- .pre-commit-config.yaml
- README.md
- pyproject.toml
- src/aiida_shell/calculations/shell.py
- tests/calculations/test_shell.py
- tests/calculations/test_shell/test_filename_stdin.txt
- tests/conftest.py
Fixes #25 
Certain codes require the input file to be passed in through the stdin file descriptor. Currently there is no way to do this. One could try to specify the `arguments` input as `['<', '{input_file}']` but the redirection argument would be quoted and read as a literal argument and so wouldn't work.
The `metadata.options.filename_stdin` input is added. When specified, the filename is defined as the `stdin_name` attribute on the `CodeInfo` instance prepared by `prepare_for_submission`. This will cause the scheduler plugin to create the command execution line:
executable < stdin_name
If `filename_stdin` is specified, the filename should be removed from the `cmdline_arguments` attribute set on the `CodeInfo`, because otherwise, the filename would be written twice on the command …
> `ShellJob`: Add `filename_stdin` input to redirect file through stdin

- README.md
- src/aiida_shell/calculations/shell.py
- tests/calculations/test_shell.py
Fixes #23 
Stdout redirection is performed automatically by the `ShellJob` and the `metadata.options.filename_stdin` input should be used to redirect a particular file to stdin. Attempting to perform these redirections "manually" through the `arguments` input will fail as the symbols will be quoted and so interpreted as a literal command line argument.
To prevent users making this mistake, a validator is added for the `arguments` input that validates that all elements are strings and that the reserved symbols are not defined.
> `ShellJob`: Raise when `<` or `>` are specified in `arguments`

- README.md
- src/aiida_shell/calculations/shell.py
- tests/calculations/test_shell.py
If a nested filepath was passed in the `filenames` input namespace, the code would except with a `FileNotFoundError` if any of the parent directories did not exist. The `ShellJob.write_single_file_data` method is updated to always create the parent directories of a filepath before attempting to write to it.
> `ShellJob`: Automatically create parent directories in `filenames`

- docs/source/howto.rst
- src/aiida_shell/engine/launchers/shell_job.py
- tests/engine/launchers/test_shell_job.py
This can be useful if the user already has a pre-configured code which specifies for example a required remote computer or the pre- and append text attributes. If the `command` is not a string, nor an `AbstractCode` a `TypeError` is raised.
> `launch_shell_job`: Accept `AbstractCode` for `command` argument

- docs/source/howto.rst
- src/aiida_shell/engine/launchers/shell_job.py
- tests/engine/launchers/test_shell_job.py
Fixes #35 
The `arguments` originally required a list of individual command line arguments. This was because it is eventually passed to the `CalcJob` which expects it in this form, such that each parameter can be properly escaped for bash.
This form is not very user-friendly, however. Often users that will use `aiida-shell` already have a workflow ready that they want to wrap with AiiDA. Currently they have to manually split the command line arguments into a list of individual args.
The `launch_shell_job` interface now accepts a `str` for `arguments` in which case it will use `shlex.split` to split the string into a list of individual arguments. The documentation is updated to exclusively use this new form.
> `launch_shell_job`: Accept string for the `arguments` argument

- src/aiida_shell/engine/launchers/shell_job.py
- tests/engine/launchers/test_shell_job.py
Fixes #37 
When the `submit` argument of `launch_shell_job` is set to `True` the job is submitted to the daemon using `aiida.engine.launch.submit`. However, when this is executed within the context of a work chain, this raises an error as `WorkChain.submit` should be used in this case instead of the global function.
The `launch_shell_job` function is updated to check whether it is called in the scope of a `WorkChain` by using `aiida.engine.Process.current()`. If the case, the `WorkChain.submit` is used instead of the global launch function.
> `launch_shell_job`: Fix bug in `submit=True` when used within work chain

- src/aiida_shell/calculations/shell.py
- src/aiida_shell/engine/launchers/shell_job.py
- tests/conftest.py
The `ShellJob` specified `tot_num_mpiprocs: 1` in the `resources` option input. This is problematic as it would always override the attribute `default_mpiprocs_per_machine` of the computer. This made it essentially impossible for a user to specify a pre-configured computer with a number of MPI processes per machine other than 1.
By removing the default, this does now mean that the `tot_num_mpiprocs` or the `mpiprocs_per_machine` key in the resources have to be set or the validation of the resources by the scheduler plugin may fail. It is not desirable that the user has to specify this manually, so the `localhost` that is automatically generated by `prepare_computer` when going through `launch_shell_job` has `default_mpiprocs_per_machine` set to 1. The same goes for the `localhost` …
> `ShellJob`: Remove `tot_num_mpiprocs` from `resources` default

- .readthedocs.yml
A recent release of `urllib3` was breaking the build, see: https://github.com/urllib3/urllib3/issues/2168
The problem does not apply to more recent versions of Python.
> Docs: Update Python version on RTD to 3.11

- .readthedocs.yml
- docs/source/howto.rst
- src/aiida_shell/calculations/shell.py
- tests/calculations/test_shell.py
This metadata input, if set to `True`, will set `CodeInfo.join_files` to `True` instead of defining `CodeInfo.stderr_name`. This will cause the submission script to look like:
date > stdout 2>&1
instead of the default:
date > stdout 2> stderr
meaning that content written to the stderr file descriptor will be redirected to the stdout file.
> `ShellJob`: Add the optional `redirect_stderr` input

- src/aiida_shell/calculations/shell.py
The exit codes in the 300-range are critical errors and nodes that have it set should not be used as cache sources. This is accomplished by defining the exit code with `invalidates_cache=True`.
> `ShellJob`: Add `invalidates_cache=True` to exit codes < 400

- src/aiida_shell/calculations/shell.py
- tests/calculations/test_shell.py
The contents of all `SinglefileData` and `FolderData` nodes in the `nodes` input namespace are written to the sandbox folder during the `prepare_for_submission`. The contents of this folder are also copied to the repository of the `CalcJobNode` representing the `ShellJob` execution.
This is undesirable, however, since the content is essentially duplicated in the data storage. The fact that all this content is already indirectly attached to the `CalcJobNode` through the input links of the relevant input node, it is not necessary to store it once again.
Therefore, all content written to the `folder` sandbox are added to the `provenance_exclude_list` which ensures that the engine does not copy the contents to the `CalcJobNode` repository.
> `ShellJob`: Do not copy contents of `nodes` to repository

- docs/source/howto.rst
- pyproject.toml
- src/aiida_shell/calculations/shell.py
- src/aiida_shell/data/__init__.py
- src/aiida_shell/data/entry_point.py
- src/aiida_shell/engine/launchers/shell_job.py
- tests/calculations/test_shell.py
- tests/data/test_entry_point.py
Although allowing to pass a parser function directly to the `parser`
input is convenient during prototyping where the parser can be defined
and used inline, at some point, parsers may become stable and reusable
in multiple places. In these cases, it makes sense to register them with
an entry point and pass that instead.
The `parser` input of the `ShellJob` now also accepts `EntryPointData`
nodes, in addition to `PickledData` nodes. The serializer will
automatically try to detect whether the passed value is a callable or a
string representing a complete entry point.
> `ShellJob`: Allow entry point strings for the `parser` input

- .github/workflows/cd.yml
- .github/workflows/ci.yml
- .github/workflows/validate_release_tag.py
- .pre-commit-config.yaml
- docs/source/conf.py
- pyproject.toml
- src/aiida_shell/__init__.py
- src/aiida_shell/calculations/__init__.py
- src/aiida_shell/calculations/shell.py
- src/aiida_shell/data/__init__.py
- src/aiida_shell/data/code.py
- src/aiida_shell/data/entry_point.py
- src/aiida_shell/data/pickled.py
- src/aiida_shell/engine/__init__.py
- src/aiida_shell/engine/launchers/__init__.py
- src/aiida_shell/engine/launchers/shell_job.py
- src/aiida_shell/parsers/__init__.py
- src/aiida_shell/parsers/shell.py
- tests/calculations/__init__.py
- tests/calculations/test_shell.py
- tests/conftest.py
- tests/data/test_code.py
- tests/data/test_entry_point.py
- tests/data/test_pickled.py
- tests/engine/launchers/test_shell_job.py
- tests/parsers/test_shell.py
- tests/test_version.py
The `ruff` tool is adopted in the pre-commit. This completely replaces the hooks `pylint`, `yapf`, `pydocstyle` and `isort`. The encoding pragma is removed since this project is Python 3 only and all files are utf-8 encoded, which is the default assumed by the Python interpreter.
For formatting, `ruff` implements the same style as `black`. The only configuration options that are changed are to set the line length to 120 and to keep single quotes, instead of double quotes.
> Devops: Migrate to `ruff` and cleanup pre-commit config

- README.md
The image was moved to `docs/source/_static` in a recent commit.
> Docs: Fix path to image in `README.md`

- docs/source/changelog.md
- docs/source/conf.py
- docs/source/index.rst
- pyproject.toml
This uses the `myst-parser` package to automatically convert the markdown format of `CHANGELOG.md` to restructured text.
> Docs: Add the changelog to the documentation

- .github/workflows/cd.yml
- .github/workflows/ci.yml
This now comes with built-in support for caching of Python dependencies allowing the workflows to be simplified by getting rid of the `cache` action.
> Devops: Update `setup-python` dependency in CI/CD to v4

- .github/workflows/cd.yml
- .github/workflows/ci.yml
- CHANGELOG.md
- docs/source/howto.rst
- pyproject.toml
- tests/calculations/test_shell.py
- tests/test_launch.py
This allows to use `SinglefileData.from_string` to simplify constructing a new node from a string, instead of having to use `io.StringIO`.
> Dependencies: Update `aiida-core~=2.4`

- docs/source/howto.rst
Fixes #65 
This can be useful, for example, to activate an conda environment in which the target command should be run.
> Docs: Add how-to on use of `prepend_text` metadata option

- docs/source/howto.rst
- src/aiida_shell/launch.py
- tests/test_launch.py
Fixes #72 
By default, `launch_shell_job` would resolve the command to the absolute filepath of the corresponding executable. This would serve two purposes: checking the command exists and increasing the reproducibility. The relative command name may be changed on the remote over time to point to another executable. By using the absolute filepath this probability is reduced, but of course not fully avoided since the file at the absolute path can still be changed on the remote.
> `launch_shell_job`: Add option to keep skip resolving of `command`

- docs/source/howto.rst
- src/aiida_shell/calculations/shell.py
- tests/calculations/test_shell.py
Fixes #68 
So far, no validation was performed on the filenames of input nodes that
would be written to the working directory that could overlap with files
written by the plugin itself, such as `stdout` and `stderr`. This could
lead to unexpected results and often calculations failing completely.
For example, if a `SinglefileData` would be written to the working
directory with the filename `stdout`, most likely because the `filename`
attribute of the node was set to this, then this would be overwritten by
the redirection of the stdout, which is redirected to the file `stdout`
by default.
A distinction is made between clashes that happen "implicitly", meaning
the filename of the `SinglefileData` or `FolderData` just happen to
overlap, compared to "explicitly" where the user specifies a …
> `ShellJob`: Detect and prevent filename clashes

- src/aiida_shell/launch.py
Before, the scratch would be just `$TMP`. This would result in a the sharded work directories of calculation jobs to be directly in the temporary directory of the filesystem and it would be difficult to clean it up. By putting it in a subdirectory that is clearly recognizable, deleting stale working directories becomes a lot easier.
> Set default localhost scratch to `$TMP/aiida_shell_scratch`

- src/aiida_shell/launch.py
- tests/test_launch.py
Fixes #78 
If the `localhost` is created before `prepare_computer` is ever called, it is possible that the property `default_mpiprocs_per_machine` is not set. This would result in the `ShellJob` validation failing if the scheduler type has a job resource class that is a subclass of `aiida.schedulers.datastructures.NodeNumberJobResource`.
The `prepare_computer` function now checks that if the `localhost` computer already exists that the `default_mpiprocs_per_machine` property is defined if the scheduler has the relevant job resource class. If that is the case, the default is set to 1.
> `prepare_computer`: Check whether `default_mpiprocs_per_machine` is set

- src/aiida_shell/calculations/shell.py
- src/aiida_shell/data/pickled.py
- tests/data/test_pickled.py
Fixes #82 
Fix `InvalidOperation` raised by `aiida-core` when pickling
To support inline custom parser functions being submitted to and
executed by the daemon, they are pickled using the `dill` library
through the `PickledData` plugin. For certain cases, the script would
hit the exception `InvalidOperation` raised by `aiida-core` in
`aiida.orm.entities.Entity.__getstate__` which is called when the
instance is attempted to be pickled by the code, which is not supported
for AiiDA's ORM entities.
The immediate cause seems to be that by default, the entire global
dictionary of the Python interpreter is pickled by `dill` and so if that
contains an AiiDA entity, the exception is hit. The entity does not even
have to be part of the parser function that is being pickled but can
just be part of …
> `PickledData`: Set `recurse=True` for `dill.dumps`

- docs/source/howto.rst
> Docs: Link to AiiDA's docs for creating custom codes

- src/aiida_shell/parsers/shell.py
- tests/parsers/test_shell.py
Fixes #92 
The `format_link_label` now checks whether the filename starts with a number, in which case the link label is prefixed with `aiida_shell_` because Python identifiers cannot start with a number.
> `ShellParser`: Prefix output filenames starting with a number

- src/aiida_shell/calculations/shell.py
- tests/calculations/test_shell.py
Fixes #58 
This is blocked because it requires this change in `aiida-core`: https://github.com/aiidateam/aiida-core/pull/6285
> `ShellJob`: Fix symlinking of remote folder data

- .github/workflows/ci.yml
- pyproject.toml
- tests/conftest.py
- tests/test_launch.py
The new fixtures allow to configure a profile with `aiida_profile` with
a storage backend that doesn't require PostgreSQL but uses the
`core.sqlite_dos` plugin instead. The fixture by default also doesn't
configure to use RabbitMQ as the broker, however, the tests in
`aiida-shell` submit to the daemon which requires a broker. Therefore
`aiida_profile` is overridden to configure RabbitMQ`.
> Devops: Make use of the improved `pytest` fixtures in `aiida-core`

- src/aiida_shell/calculations/shell.py
- tests/calculations/test_shell.py
Fixes #94 
The `metadata.options.output_filename` is defined by the `CalcJob` base class, and so is inherited by the `ShellJob`. The `ShellParser` plugin actually correctly deals with this case, however, the `ShellJob` only partially so. It did actually redirect stdout to this custom output file, however, it did not instruct for the custom output file to be retrieved, causing the `ERROR_OUTPUT_STDOUT_MISSING` to be returned.
The bug is fixed by replacing the default stdout filename in the `retrieve_temporary_list` with the custom `output_filename`.
> `ShellJob`: Add `metadata.options.output_filename` to retrieve list

- docs/source/howto.rst
- src/aiida_shell/launch.py
- tests/test_launch.py
The `metadata` passed to the `launch_shell_job` is just supposed to expose the same input of the `ShellJob` and essentially forward it. However, the `computer` input was expected to be passed nested inside the `options` namespace, even though it is defined as a top-level metadata input. This makes the inputs for `launch_shell_job` dfifferent from the `ShellJob` causing unnecessary confusion. The `computer` input should now be specified as a top-level metadata input for the `launch_shell_job` wrapper as well.
> `launch_shell_job`: Move `computer` to top-level of `metadata`

- docs/source/howto.rst
- src/aiida_shell/calculations/shell.py
- tests/calculations/test_shell.py
Fixes #101 
Any argument that did not contain a placeholder would simply be appended as is, but this would cause escaped curly braces not to be resolved. The solution is to just call `argument.format()` in this case, letting the string formatter take care of resolving the escaped characters.
> `ShellCalculation`: Resolve escaped curly braces in arguments

- src/aiida_shell/launch.py
- tests/test_launch.py
Commands like `git diff`, `verdi status` or `python script.py` will fail with different opaque error messages. We add a check that the command consists only out of one argument to give the user a clearer error message.
> Improve error message of commands consisting of multiple arguments

- src/aiida_shell/launch.py
This PR refactors the `launch_shell_job` function by extracting the input preparation logic into a new helper function, `prepare_shell_job_inputs`. The launch_shell_job function now calls this helper function to prepare the inputs before submitting or running the job. This allows others to reuse the input preparation logic elsewhere if needed.
Use case: 
In `aiida-workgraph`, we use the [prepare_for_shell_task](https://github.com/aiidateam/aiida-workgraph/blob/5bf734af360b12e238ac8955f8eb0512fb19fb29/aiida_workgraph/engine/utils.py#L132-L164) function to prepare inputs for the `ShellJob` task, as in the `launch_shell_job`. The challenge, however, is that we need to keep the `prepare_for_shell_task` function up to date with any changes made to `launch_shell_job`. By extracting the input …
> Add a helper function to prepare the inputs

- .readthedocs.yml
See https://about.readthedocs.com/blog/2024/12/deprecate-config-files-without-sphinx-or-mkdocs-config/
> Devops: Add explicit `sphinx.configuration` key to RTD conf

- src/aiida_shell/calculations/shell.py
- tests/calculations/test_shell.py
- tests/conftest.py
- tests/test_launch.py
The `filenames` input was not taken into account for `RemoteData` input nodes.
> `ShellJob`: Fix `RemoteData` handling
